name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Write key
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      run: |
        if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
        echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
        echo keyAlias='${{ secrets.ALIAS }}' >> local.properties
        echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> local.properties
        echo storeFile='key.jks' >> local.properties
        echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease assembleDebug

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: app/build/outputs/apk
